version: '3'
services:
    php-admin:
        container_name: php-admin
        build:
            context: ./html
            dockerfile: ../docker/php/Dockerfile
        volumes:
            - ./html:/usr/share/nginx/html:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        # depends_on:
        #     - db-admin
        restart: always
        tty: true
        privileged: true
        networks:
            - tekko_app_admin_nw
            - tekko_db_nw

    nginx-admin:
        image: nginx:1.14.2-alpine
        container_name: nginx-admin
        ports:
            - "8001:80"
        volumes:
            - ./docker/nginx/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./html:/usr/share/nginx/html:cached
            - ./docker/hosts:/etc/hosts:cached
        links:
            - php-admin
        networks:
            - tekko_app_admin_nw

networks:
    tekko_app_admin_nw:
        driver: bridge
    tekko_db_nw:
        external: true
        
